### ISSUE TITLE
Magnet Hole Slit Removed

### ISSUE THREAD

**Issue by jgnoel86** [kennetek/gridfinity-rebuilt-openscad#20]
When you switched to the hole style, it looks like you removed the hole slit unless the user selects to want the screw hole as well. Was this deliberate or just just a small oversight? I don't need screw holes, but really wanted the hole slit.

**Comment by kennetek** [comment]
The slit shouldn't be necessary if its just the magnet without screw holes. Like, if there's no screw hole, then the slicer just bridges that gap like any other overhang, because its flat. That's why I removed it, so yes it was intentional. Is there a reason besides slicing that you want it?

**Comment by jgnoel86** [comment]
Nope, that's perfect, I'm still new to printing in general, so wasn't aware. I do appreciate your tool though it's awesome!

**Comment by Ramblurr** [comment]
Hi there! This may be a dumb question, but I'm planning my gridfinity setup and am wondering what the slit option is for?

**Comment by kennetek** [comment]
It is to allow slicing of a mid-air hole for screws. Zack originally put screw holes in the model so that they could be bolted down if the model was really top heavy. I personally do not use screws, so the extra hole and slit is unnecessary. The technique is described here: https://github.com/gregsaun/maker_cheatsheet/blob/master/3d_printing/techniques.md#mid-air-hole
