### ISSUE TITLE
Erroneous geometry beyond body of 1u

### ISSUE THREAD

**Issue by BenBreaksThings** [kennetek/gridfinity-rebuilt-openscad#46]
When creating a NxNx1 bin (not tested in lite or vase), there is a single line perimeter protrusion out of the bottom exterior that interferes with the exterior chamfer. Changing it from 1u to anything larger will eliminate the error.
![Screen Shot 2023-01-09 at 12 57 38 PM](https://user-images.githubusercontent.com/78265023/211375893-95b296e7-f7b0-4241-bde0-7d982fc5dfa1.png)
![Screen Shot 2023-01-09 at 12 56 25 PM](https://user-images.githubusercontent.com/78265023/211375894-f2618e32-d597-48f1-a67d-bd7ddebbe4d5.png)

**Comment by Ruudjhuu** [comment]
This artifact is due to the lip needing too more vertical space than the height of the bin. However, a bin of `gridz =1` is useless, the height is like 1 mm taller than the base. For now your workaround would be to disable the lip and probably add 1 to gridz to make the bin usefull.

We can go forward with this artifact multiple ways here.
* Disable the creation of bins where `gridz <= 1`. They are useless as the base is almost the same height
* Shorten the base in the z height. Keep in might this might break compatibility with custom created bins as the is always the same.
* Add the missing height by removing the lip to the wall when lip is disabled. This keeps the total height of a bin created with `enable_lip = 0` the same size as a bin created with `enable_lip = 1` which makes a bin of 1u not useless anymore.
* set`enable_lip = 0` by default when `gridz <= 1`
* Add a cut which cuts everything below the minimal allowed bin height (without base) which allows the user to create anything they want, even a 1u bin with a (partial) lip.
